### ISSUE TITLE
Display Ctrl, Shift and/or Alt + RMB /LMB when clicking while holding the key

### ISSUE THREAD

**Issue by tamomilan** [Phaiax/Key-n-Stroke#30] opened 2018-02-19 22:06 UTC
Hi. I could not find any settings allowing to display the keys Ctrl, Alt, or Shift without typing another key. It would be great if they could be displayed when holding them while mouseclick. (e.g. to explain why the transformation of a frame is proportional.)
Maybe it would be even better, if they are displayed as key-icons besides the mouse-icon or, alternatively, e.g. clicking left mousebutton while holding ctrl key is displayed as "ctrl+lmb" in the textarea.

**Comment by cloo** [comment] 2018-04-13 12:25
agree to @tamomilan - I cannot use it for teaching software without Ctr/Alt/Shift..

**Comment by Phaiax** [comment] 2018-04-13 13:41
I know.
The problem is, currently I use windows only very occasionally. 
But this project is open source. You can fork it, change it and make a pull request, and I will happily accept it and create new binaries for download.
I don't know your background but even if you don't program, you may know someone who can help you. This is an minor change, so give it a try.
Best would be a checkbox in the settings.
If the user checks or unchecks the box, you disable the handler that does the Ctrl+Alt+Shift stuff.
If you need more help, I can point you to the relevant places in the code.

Daniel. 

Am 13. April 2018 14:25:16 MESZ schrieb dudenas <notifications@github.com>:
>agree to @tamomilan - I cannot use it for teaching software without
>Ctr/Alt/Shift..
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Phaiax/PxKeystrokesForScreencasts/issues/30#issuecomment-381119151

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Phaiax** [comment] 2021-06-05 22:19
Fixed in release v1.0.0

**Closed by Phaiax** 2021-06-05 22:19 UTC
Labels: v2.0
