### ISSUE TITLE
Instability Stops working

### ISSUE THREAD

**Issue by mtelesha** [Phaiax/Key-n-Stroke#5] opened 2016-01-21 19:02 UTC
Here is a video of it stopping: https://youtu.be/EtazaEPGQzk

It will even fail to relaunch. I am using a screen recorder Open Broadcast Streamer https://obsproject.com/

While the screen is being recorded it works for about 45 seconds at a time then freezes.

**Comment by Phaiax** [comment] 2016-01-24 02:47
I have fixed some bugs and added new features, but that special bug did only occured once during testing and i could not reproduce it.
Maybe it is fixed, maybe not.

**Comment by Phaiax** [comment] 2021-06-05 22:34
hopefully fixed with v1.0.0

**Closed by Phaiax** 2021-06-05 22:34 UTC
